spring:
  application:
    name: palate
  datasource:
    # Use environment variables for security. 
    # Render will provide the DB_URL, DB_USERNAME, and DB_PASSWORD
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    # Use the PostgreSQL dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# LOGGING CONFIGURATION
logging:
  level:
    root: INFO
    # Ensure this matches your project's package structure
    com.app.palate.order: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"